### PR TITLE
fix(sdk): add missing meta property to inscription object

### PR DESCRIPTION
**Pull request by kevzzsk**
This PR adds the missing optional `meta` property to `InscriptionsEntity` interface.

As per [OIP-1](https://github.com/sadoprotocol/oips/blob/main/oip-01-inscription-metadata.md), the `meta` object is returned by the [utxo/unspents](https://github.com/sadoprotocol/utxo-api/blob/a2cb353a1ef80c77307af2915b8b10d195d4c144/src/lookup.js#L126-L143) endpoint.

### CODE REVIEW

**Comment by iamcrazycoder** [comment]
@kevzzsk 
- What are the fields that can possibly reside in `meta` object?
- Will `meta` be nested or single-level?
- Can you list down the possible data types that will possibly be in properties of the `meta` object? (string, number, array, etc.)

**Comment by kevzzsk** [comment]
`meta` technically can be any form of data actually. Only in [OIP-1](https://www.oips.io/oip-01-inscription-metadata), it is defined to be of a certain JSON format.
Looking at the underlying utxo-api parsing, it does a `JSON.parse` which means `meta` can be `Record` type of any level, array or string.

**Comment by iamcrazycoder** [comment]
@kevzzsk Makes sense. What fields is Ordzaar planning to include in `meta`? I am curious to know.

**Review by iamcrazycoder — APPROVED** [review]
utACK

**Comment by kevzzsk** [comment]
for ordzaar, meta will just be a json format that follows [OIP-2](https://www.oips.io/oip-02-verifiable-ordinal-collection) standard.

**Pull request merged**
